### PR TITLE
[Patch]: Fix negative tool durability

### PR DESCRIPTION
**Pull request by Steveplays28**
This just randomly happens for some reason, removing this mixin fixes it.

### CODE REVIEW

**Comment by SigmundGranaas** [comment]
I had a bit of a look at this, and we cannot completely remove the getMaxDamage mixin, because it will then use the items default durability when figuring out when a tool break, which will make Forgero tools with dynamic durabilty break before they actually run out of durability:

If we think there's something wrong happening here, we can use this as a fallback:

```
		@Inject(method = "getMaxDamage", at = @At("HEAD"), cancellable = true)
	public void getCustomDurability(CallbackInfoReturnable<Integer> cir) {
		if (this.getItem() instanceof DynamicDurability tool) {
			@SuppressWarnings("DataFlowIssue")
			ItemStack stack = (ItemStack) (Object) this;
			int durability = tool.getDurability(stack);
			if (durability > 0) {
				cir.setReturnValue(durability);
			} else {
				Forgero.LOGGER.error("Somehow the Durability of the tool {}, was {}. This should never happen", stack, durability);
			}
		}
	}
```

**Comment by Steveplays28** [comment]
Alright, that seems like a good compromise.
I'll add it to the PR.

**Comment by Steveplays28** [comment]
Added your suggested changes, should be ready for merge now.

**Comment by SigmundGranaas** [comment]
Oh, wait can we set the target branch to 1.19? I haven't switch to 1.20 yet

**Comment by Steveplays28** [comment]
I tested on `1.20.1` myself, works there
I can do some more testing real quick

**Pull request merged**
