### PR TITLE
AE2 Materials

### LINKED ISSUE #443: Applied energistics materials
https://modrinth.com/mod/ae2

Materials:
- Certus Quartz
- Charged Certus Quartz (same tool texture)

### PR DESCRIPTION
**Pull request by lluminanoctis**
Added 3 materials:

- Nether Quartz
- Certus Quartz
- Fluix

Fluix tools and weapons will most likely need to be amended (with looting 1 on swords and fortune 1 on tools) when enchantments embed functionality is out.

Closes #443

### CODE REVIEW

**Comment by SigmundGranaas** [comment]
Nice work!
Hopefully I'll have time to boot it up and check it out tomorrow. Pack and materials looks well made and organized.

**Comment by Steveplays28** [comment]
Do the certus quartz tools work with charged certus quartz too? Small nitpick but super nice work :D

**Comment by SigmundGranaas** [comment]
Don't worry about the gametest, seems like something is wrong when pulling new dependencies

**Comment by lluminanoctis** [comment]
@Steveplays28 no, I added it only for regular certus crystals but it would be good if same part could be crafted both with regular and charged ones. Using c:certus_quartz tag as id did not work, @SigmundGranaas maybe you would know more?

**Comment by SigmundGranaas** [comment]
Currently, tags are not usable as a container id. I am looking for how to solve this problem, but it will likely be a major refactor of the core, so I won't do it unless I have a significant amount of time available to fix it. 

The current easiest solution for this is to create two material files where one uses the other one as parent to copy all of its attributes, and only changes the name.

**Comment by lluminanoctis** [comment]
@SigmundGranaas but wouldn't that create duplicate parts?

**Comment by SigmundGranaas** [comment]
Sortof, there would be one charged and one normal.

**Comment by lluminanoctis** [comment]
Well, thats not ideal so I guess making charged certus quartz available as a material will wait.

**Comment by SigmundGranaas** [comment]
Yeah, that's probably a good call

**Comment by lluminanoctis** [comment]
One quick note I just saw you have added nether quartz for 0.11, maybe then it would be worth moving nether quartz material from here to forgero-vanilla? I added it mainly because AE2 adds nether quartz tools.

**Comment by SigmundGranaas** [comment]
Yeah I'll probably use your material and move it for 0.11. Having it in compat makes it a lot easier

**Pull request merged**
