### PR TITLE
Mod Menu integration

### PR DESCRIPTION
**Pull request by Steveplays28**
- Added Mod Menu metadata to the `fabric.mod.json` files of every component (Discord link, parent mod, library tag for child mods)
- Improved every `fabric.mod.json` files (fixed some metadata properties like the homepage, sources, and the dependencies, also added contributors)
- Rewrote config system (removed `Deserializer` class, simplified configuration interface and classes)

TODO:
- [x] Mod Menu config screen button using their [API](https://github.com/TerraformersMC/ModMenu/wiki/API)
- [x] Custom UI widgets for types used in the config
- [x] Custom config screen
- [x] Saving the config
- [x] Fix text field issues

### CODE REVIEW

**Comment by SigmundGranaas** [comment]
That's neat! I have been reminding myself to fix all of these things, but always forget it...

For the modmenu integration, it's fine to put a hard dependency in the fabric compat module, and add the required classes there.

Once this is ready, I'll probably bundle another structure and release this alongside 0.10.6. Welcome to the contributors club!

**Comment by Steveplays28** [comment]
Got it, thank you!

**Comment by SigmundGranaas** [comment]
Would you mind adding Aulluna to the list of contributors as well? He hasn't pushed directly to the repo, but has made some models and stuff for me.

**Comment by Steveplays28** [comment]
Done, added Aulluna to the contributors list!

**Comment by Steveplays28** [comment]
It do be done now

<details>
<summary>Gallery images</summary>

image
image

</details>

**Pull request merged**
