### PR TITLE
fix: remove category tag on composite attribute

### PR DESCRIPTION
**Pull request by rapus95**

### CODE REVIEW

**Comment by rapus95** [comment]
bes to squash commits only keeping the first message

**Comment by SigmundGranaas** [comment]
All done here?

**Comment by rapus95** [comment]
these are only the ones for the minecraft-vanilla. When trying the larger codebase with compat etc, there were way more. So many I didn't start it by hand. Should consider writing a tool for it lol

**Comment by rapus95** [comment]
but for minecraft-vanilla stuff, this is complete.

**Comment by SigmundGranaas** [comment]
Good work!

**Pull request merged**
