### PR TITLE
Update dependencies to 1.19.4 and fix Mod Menu invisible mod

### LINKED ISSUE #584: ModMenu 6.2.0 and 6.2.1 crashes my game, seems to be incompatible with Forgero
Here's the two crash reports, think they're for each version:

[crash-2023-04-21_06.03.56-server.txt](https://github.com/SigmundGranaas/forgero/files/11290793/crash-2023-04-21_06.03.56-server.txt)
[crash-2023-04-21_06.08.04-server.txt](https://github.com/SigmundGranaas/forgero/files/11290794/crash-2023-04-21_06.08.04-server.txt)

### PR DESCRIPTION
**Pull request by Steveplays28**
Disabled Patchouli compat since it hasn't been updated yet, this allows the game to load a world without crashing.
Also removed unnecessary temporary files that should be excluded by the `.gitignore` file.

Mod Menu compat still needs work, since the parent mod doesn't have a name, nor an icon, and the settings button is back on the Fabric compat child mod instead of the parent mod because I disabled the mixin, since it was causing a crash on 1.19.4.

EDIT: `.gitignore` file changes got merged into `1.19`.
DOUBLE EDIT: Fixed Mod Menu invisible mod issues.

### CODE REVIEW

**Comment by SigmundGranaas** [comment]
Looks good!

**Review by SigmundGranaas — APPROVED** [review]

**Comment by Steveplays28** [comment]
Still do want to fix the Mod Menu stuff before I merge though

**Comment by SigmundGranaas** [comment]
Do you want to fix the nested mod structure as well?

**Comment by Steveplays28** [comment]
Not sure what's with the game test but should be ready for merge.

**Comment by SigmundGranaas** [comment]
I believe the gametests are using an unsupported gradle version

**Comment by SigmundGranaas** [comment]
I made some changes to the modmenu structure of the mods to follow the guidelines for "fake" wrapper mods like the the one we use. https://github.com/TerraformersMC/ModMenu/wiki/API#parents

Also, removing resources from the Fabric module has the consequence of making it impossible to build the mod, because loom requires the wrapper to be a valid mod, so it needs the fabric.mod.json file. I also added a new gametest to check this.

I also went ahead and deleted the modmenu mixin, as I don't think it will be possible to maintain it when modmenu updates their code. Ideally the settings button should also transfer to the parent, but maybe this is something we should create an isssue for on their github to allow settings button to transfer to parent through the modmenu json api.

Overall the whole 1.19.4 branch is a lot cleaner and stable now, so good job!

**Comment by Steveplays28** [comment]
Alrighty, I'll fix it up in a bit and rebase the branch.

**Comment by SigmundGranaas** [comment]
Did you have the patchouli fix ready or should I just patch it real quick?

**Comment by Steveplays28** [comment]
Let me do that real quick kek

**Pull request merged**
