### PR TITLE
Betternether

### PR DESCRIPTION
**Pull request by JorisDeBeer**
BETTERNETHER COMPAT YES

### CODE REVIEW

**Comment by Steveplays28** [comment]
We cram this into the next release candidate as usual, let's go 🤣 
Nice work Joris as always

### **One thing though to whoever presses the merge PR button: do you mind pressing the dropdown and squash merging the PR?**

This is so the PR can be cherrypicked easily. Yes I'm abusing Markdown headers for this one

**Comment by SigmundGranaas** [comment]
No worries Steve, I have defaulted to squash and merge for PR's now

**Comment by SigmundGranaas** [comment]
Awesome work man :star:

**Comment by Steveplays28** [comment]
Awesome! Good to hear squash is default now.
Congrats on the merge Joris!

**Pull request merged**
