### PR TITLE
Fix gametest

### PR DESCRIPTION
**Pull request by Steveplays28**
Changes the mixins to other mods to use the `@Pseudo` annotation instead of a mixin plugin, which removes the dependency on ASM added by the interface and thus fixes the error on PR gametests.
The `@Pseudo` annotation should still make sure the classes only get mixed into when the mods are actually present at runtime.

### CODE REVIEW

**Comment by Steveplays28** [comment]
Just realised my branch was out of date. Hold up.

**Comment by Steveplays28** [comment]
Still failed. Not sure why it's still referencing the class that doesn't exist in the code anymore

**Comment by SigmundGranaas** [comment]
Damn, that's such a weird issue. I'll try to see if I can figure something out.

**Comment by SigmundGranaas** [comment]
It's so weird that it didn't fail the gametest when this pr was introduced

**Comment by Steveplays28** [comment]
Yeah defo, that entire PR works just fine.
Maybe GitHub actions only updates classes once you merge or something?

Just a random (illogical) shout

**Comment by SigmundGranaas** [comment]
I don't know, my last guess is changing the test runner to use openjdk instead of adoptium, that's my only guess

**Comment by Steveplays28** [comment]
Could change that later if you want to try

**Pull request closed without merging**
